# Generated by Django 2.1.7 on 2019-05-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbscrypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.CharField(max_length=20)),
                ('exchangebuy', models.FloatField()),
                ('exchangesell', models.FloatField()),
                ('percentage', models.FloatField()),
                ('buyprice', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('gain', models.FloatField()),
                ('volumesizebuy', models.FloatField(default=233)),
                ('volumesizesell', models.FloatField(default=233)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='arbscrypto',
            unique_together={('percentage', 'buyprice')},
        ),
    ]
