# Generated by Django 2.1.7 on 2019-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20190504_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbscrypto',
            name='exchangebuy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arbscrypto',
            name='exchangesell',
            field=models.CharField(max_length=50),
        ),
    ]
