# Generated by Django 2.0.2 on 2019-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190324_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='circulating_supply',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='max_supply',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
